.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/App.xaml.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/App.xaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransport_Management_System_WPF::App\fP"
.br
.RI "Interaction logic for \fBApp\&.xaml\fP "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTransport_Management_System_WPF\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
