.TH "C:/Users/School User/Code/TMS-Dump/SampleWFPUsingPages/SampleWFPUsingPages Directory Reference" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/SampleWFPUsingPages/SampleWFPUsingPages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdminClasses\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdminPage\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPage1\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPage2\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBViewLogDetailsPage\&.xaml\&.cs\fP"
.br
.in -1c
