.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/TMSwPages Directory Reference" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/TMSwPages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdminClasses\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdminPage\&.xaml\&.cs\fP"
.br
.RI "This file contains the Interaction Logic for the Admin Page (code-behind) 
.br
 "
.ti -1c
.RI "file \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.xaml\&.cs\fP"
.br
.RI "This file contains the Interaction Logic for the Main navigation window Page (code-behind) 
.br
 "
.ti -1c
.RI "file \fBPage1\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPage2\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBViewLogDetails\&.xaml\&.cs\fP"
.br
.in -1c
