.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF Directory Reference" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdminClasses\&.cs\fP"
.br
.RI "This file contains the admin functionality 
.br
 "
.ti -1c
.RI "file \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBBuyerClass\&.cs\fP"
.br
.RI "This file contains the buyer functionality\&. "
.ti -1c
.RI "file \fBCarrier\&.cs\fP"
.br
.RI "This file contains the admin functionality 
.br
 "
.ti -1c
.RI "file \fBContract\&.cs\fP"
.br
.RI "This file contains the buyer functionality\&. "
.ti -1c
.RI "file \fBMainWindow\&.xaml\&.cs\fP"
.br
.RI "This file contains the admin functionality 
.br
 "
.ti -1c
.RI "file \fBMappingClass\&.cs\fP"
.br
.RI "This file contains the functionality for Route Calculation\&. This will be used by the Planner\&. "
.ti -1c
.RI "file \fBmysqlConnector\&.cs\fP"
.br
.RI "This file contains the admin functionality 
.br
 "
.ti -1c
.RI "file \fBPlannerClass\&.cs\fP"
.br
.RI "This file contains the Planner functionality\&. "
.ti -1c
.RI "file \fBSQL_Query\&.cs\fP"
.br
.RI "This file contains the SQL Querys to the cmp\&. 
.br
 "
.ti -1c
.RI "file \fBSQL_Query_TMS\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimePass\&.cs\fP"
.br
.RI "This file contains the functionality to simulate time\&. 
.br
 "
.in -1c
