.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/packages Directory Reference" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/packages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBouncyCastle\&.1\&.8\&.3\&.1\fP"
.br
.in -1c
