.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/TMSwPages/obj/Debug/MainNavWindow.g.i.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/TMSwPages/obj/Debug/MainNavWindow.g.i.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMSwPages::MainWindow\fP"
.br
.RI "\\summary This is the Interaction Logic for the main nagivation window "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMSwPages\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
