.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/MappingClass.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/MappingClass.cs \- This file contains the functionality for Route Calculation\&. This will be used by the Planner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.RouteData\fP"
.br
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.RouteSumData\fP"
.br
.ti -1c
.RI "class \fBTransport_Management_System_WPF\&.CityNode\fP"
.br
.RI "This class runs the \fBCityNode\fP functionality\&. "
.ti -1c
.RI "class \fBTransport_Management_System_WPF\&.MappingClass\fP"
.br
.RI "This class will be used by the planner to calculate route information for trip tickets\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTransport_Management_System_WPF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the functionality for Route Calculation\&. This will be used by the Planner\&. 


.PP
\fBDate\fP
.RS 4
November 20, 2019 
.RE
.PP
\fBAuthor\fP
.RS 4
8000 Cigarettes - Duane 
.RE
.PP
\fBSee also\fP
.RS 4
\fBPlannerClass\&.cs\fP
.RE
.PP
This file holds the struct definitions that will be used to pass data from class to class\&. 
.br
 It also holds the definition Mapping class\&. This class has the functionality that is needed to calculate route data for trip tickets\&.
.PP
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
