.TH "md__c_1__users__school__user__code__t_m_s-_dump__transport__management__system__w_p_f_packages__bouncy_castle.1.8.3.1__r_e_a_d_m_e" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__school__user__code__t_m_s-_dump__transport__management__system__w_p_f_packages__bouncy_castle.1.8.3.1__r_e_a_d_m_e \- The Bouncy Castle Crypto Package For C Sharp 
The Bouncy Castle Crypto package is a C# implementation of cryptographic algorithms and protocols, it was developed by the Legion of the Bouncy Castle, a registered Australian Charity, with a little help! The Legion, and the latest goings on with this package, can be found at \fChttp://www\&.bouncycastle\&.org\fP\&. In addition to providing basic cryptography algorithms, the package also provides support for CMS, TSP, X\&.509 certificate generation and a variety of other standards such as OpenPGP\&.
.PP
The Legion also gratefully acknowledges the contributions made to this package by others (see \fChere\fP for the current list)\&. If you would like to contribute to our efforts please feel free to get in touch with us or visit our \fCdonations page\fP, sponsor some specific work, or purchase a support contract through \fCCrypto Workshop\fP\&.
.PP
Except where otherwise stated, this software is distributed under a license based on the MIT X Consortium license\&. To view the license, \fCsee here\fP\&. The OpenPGP library also includes a modified BZIP2 library which is licensed under the \fCApache Software License, Version 2\&.0\fP\&.
.PP
\fBNote\fP: this source tree is not the FIPS version of the APIs - if you are interested in our FIPS version please contact us directly at \fCoffice@bouncycastle\&.org\fP\&.
.SH "Mailing Lists"
.PP
For those who are interested, there are 2 mailing lists for participation in this project\&. To subscribe use the links below and include the word subscribe in the message body\&. (To unsubscribe, replace \fBsubscribe\fP with \fBunsubscribe\fP in the message body)
.PP
.IP "\(bu" 2
\fCannounce-crypto-csharp-request@bouncycastle\&.org\fP 
.br
 This mailing list is for new release announcements only, general subscribers cannot post to it\&.
.IP "\(bu" 2
\fCdev-crypto-csharp-request@bouncycastle\&.org\fP 
.br
 This mailing list is for discussion of development of the package\&. This includes bugs, comments, requests for enhancements, questions about use or operation\&.
.PP
.PP
**NOTE:**You need to be subscribed to send mail to the above mailing list\&.
.SH "Feedback"
.PP
If you want to provide feedback directly to the members of \fBThe Legion\fP then please use \fCfeedback-crypto@bouncycastle\&.org\fP, if you want to help this project survive please consider \fCdonating\fP\&.
.PP
For bug reporting/requests you can report issues here on github, via feedback-crypto if required, and we also have a \fCJira issue tracker\fP\&. We will accept pull requests based on this repository as well\&.
.SH "Finally"
.PP
Enjoy! 
