.TH "C:/Users/School User/Code/TMS-Dump/SampleWFPUsingPages/SampleWFPUsingPages/obj/Debug/Page2.g.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/SampleWFPUsingPages/SampleWFPUsingPages/obj/Debug/Page2.g.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSampleWFPUsingPages::Page2\fP"
.br
.RI "\fBPage2\fP "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSampleWFPUsingPages\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
