.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/PlannerClass.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/PlannerClass.cs \- This file contains the Planner functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.Customer\fP"
.br
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.Trip_Ticket\fP"
.br
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.Trip_Ticket_Line\fP"
.br
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.Location\fP"
.br
.ti -1c
.RI "struct \fBTransport_Management_System_WPF\&.Truck\fP"
.br
.ti -1c
.RI "class \fBTransport_Management_System_WPF\&.PlannerClass\fP"
.br
.RI "This class runs the \fBPlanner\fP functionality\&. "
.ti -1c
.RI "class \fBTransport_Management_System_WPF\&.PlannerClass\&.Planner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTransport_Management_System_WPF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the Planner functionality\&. 


.PP
\fBDate\fP
.RS 4
November 20, 2019 
.RE
.PP
\fBAuthor\fP
.RS 4
8000 Cigarettes - Duane,Megan,Ivan,Zena 
.RE
.PP
\fBSee also\fP
.RS 4
MainWindow\&.xaml
.RE
.PP
See the class description for the more details 
.br
.PP
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
