.TH "SampleWFPUsingPages::ViewLog" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleWFPUsingPages::ViewLog \- \fBViewLog\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page, and IComponentConnector\&.
.SH "Detailed Description"
.PP 
\fBViewLog\fP 


.PP
Definition at line 42 of file ViewLog\&.g\&.i\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
