.TH "SampleWFPUsingPages.TMSLog" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleWFPUsingPages.TMSLog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMSLog\fP (string nUnparsed)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBlogPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogMethod\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogMessage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBSV\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBlogTime\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SampleWFPUsingPages\&.TMSLog\&.TMSLog (string nUnparsed)"

.SH "Property Documentation"
.PP 
.SS "string SampleWFPUsingPages\&.TMSLog\&.BSV\fC [get]\fP, \fC [set]\fP"

.SS "string SampleWFPUsingPages\&.TMSLog\&.logClass\fC [get]\fP, \fC [set]\fP"

.SS "string SampleWFPUsingPages\&.TMSLog\&.logMessage\fC [get]\fP, \fC [set]\fP"

.SS "string SampleWFPUsingPages\&.TMSLog\&.logMethod\fC [get]\fP, \fC [set]\fP"

.SS "string SampleWFPUsingPages\&.TMSLog\&.logPath\fC [get]\fP, \fC [set]\fP"

.SS "DateTime SampleWFPUsingPages\&.TMSLog\&.logTime\fC [get]\fP, \fC [set]\fP"

.SS "string SampleWFPUsingPages\&.TMSLog\&.logType\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
