.TH "SampleWFPUsingPages::ViewLogDetailsPage" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleWFPUsingPages::ViewLogDetailsPage \- \fBViewLogDetailsPage\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page, Page, IComponentConnector, Page, Page, IComponentConnector, Page, and IComponentConnector\&.
.SH "Detailed Description"
.PP 
\fBViewLogDetailsPage\fP 

Interaction logic for ViewLogDetailsPage\&.xaml
.PP
Definition at line 41 of file ViewLogDetailsPage\&.g\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
