.TH "C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/SQL_Query.cs" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/School User/Code/TMS-Dump/Transport Management System WPF/Transport Management System WPF/SQL_Query.cs \- This file contains the admin functionality 
.br
  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransport_Management_System_WPF\&.SQL_Query\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTransport_Management_System_WPF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the admin functionality 
.br
 


.PP
\fBDate\fP
.RS 4
November 20, 2019 
.RE
.PP
\fBAuthor\fP
.RS 4
8000 Cigarettes - Megan 
.RE
.PP
\fBSee also\fP
.RS 4
\fBMainWindow\&.xaml\fP
.RE
.PP
This file holds the functionality of the \fBAdmin\fP class\&. The \fBAdmin\fP has the ability to view logs as specified by time period, view details of specific logs, alter where the log files are stored, initiate backups of the TMS database, choose where the TMS db is backed up to, alter the Carrier Data Table, the Route Table, and the Rate / Fee Tables\&. 
.br
.PP
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
