.TH "TMSwPages.BackupTMS" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages.BackupTMS \- This class executes the \fBAdmin\fP functions related to Backup\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class executes the \fBAdmin\fP functions related to Backup\&. 

This class can initiate the backup of the TMS database and change where the backup is stored\&.
.PP
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
