.TH "TMSwPages::Page1" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages::Page1 \- \fBPage1\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page, Page, IComponentConnector, Page, and IComponentConnector\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "public \fBPage1\fP ()"
.br
.ti -1c
.RI "private void \fBButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "internal System Windows Controls ListBox \fBpeopleListBox\fP"
.br
.ti -1c
.RI "private bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPage1\fP 

Interaction logic for Page1\&.xaml
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public TMSwPages::Page1::Page1 ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "private void TMSwPages::Page1::Button_Click (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "void System Windows Markup IComponentConnector TMSwPages::Page1::Connect (int connectionId, object target)\fC [private]\fP"

.SS "void System Windows Markup IComponentConnector TMSwPages::Page1::Connect (int connectionId, object target)\fC [private]\fP"

.SS "public void TMSwPages::Page1::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SS "public void TMSwPages::Page1::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SH "Member Data Documentation"
.PP 
.SS "private bool TMSwPages::Page1::_contentLoaded\fC [private]\fP"

.SS "internal System Windows Controls ListBox TMSwPages::Page1::peopleListBox\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
