.TH "TMSwPages.TMSLog" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages.TMSLog \- This class instantiates and stores a \fBTMSLog\fP object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMSLog\fP (string nUnparsed)"
.br
.RI "Constructor for the \fBTMSLog\fP class\&. "
.ti -1c
.RI "\fBTMSLog\fP (string nUnparsed)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBlogPath\fP\fC [get, set]\fP"
.br
.RI "Data for each individual log (not currently protected) "
.ti -1c
.RI "string \fBlogClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogMethod\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogMessage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBSV\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBlogTime\fP\fC [get, set]\fP"
.br
.RI "Bar separated values\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class instantiates and stores a \fBTMSLog\fP object\&. 

This is mainly just called by the \fBTMSLogger\fP class\&.
.PP
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMSwPages\&.TMSLog\&.TMSLog (string nUnparsed)"

.PP
Constructor for the \fBTMSLog\fP class\&. This takes in a specifically formatted string of BSV (Bar separated values) and parses it to create a new log object\&. If the string isn't parsed correctly, a new log is created which acknowledges this\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP nUnparsed An incoming value meant to be parsed into a log object 
.RE
.PP
\fBSee also\fP
.RS 4
Regex\&.Matches(), nUnparsed\&.Split(), DateTime\&.Parse() 
.RE
.PP
\fBReturns\fP
.RS 4
Creates a \fBTMSLog\fP object
.RE
.PP
.PP
 Used in Logger / LogIt call
.PP
Used in reading in from a file
.PP
Used in formatting error
.SS "TMSwPages\&.TMSLog\&.TMSLog (string nUnparsed)"
Used in Logger / LogIt call
.PP
Used in reading in from a file
.PP
Used in formatting error
.SH "Property Documentation"
.PP 
.SS "string TMSwPages\&.TMSLog\&.BSV\fC [get]\fP, \fC [set]\fP"

.SS "string TMSwPages\&.TMSLog\&.logClass\fC [get]\fP, \fC [set]\fP"

.SS "string TMSwPages\&.TMSLog\&.logMessage\fC [get]\fP, \fC [set]\fP"

.SS "string TMSwPages\&.TMSLog\&.logMethod\fC [get]\fP, \fC [set]\fP"

.SS "string TMSwPages\&.TMSLog\&.logPath\fC [get]\fP, \fC [set]\fP"

.PP
Data for each individual log (not currently protected) 
.SS "DateTime TMSwPages\&.TMSLog\&.logTime\fC [get]\fP, \fC [set]\fP"

.PP
Bar separated values\&. 
.SS "string TMSwPages\&.TMSLog\&.logType\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
