.TH "TMSwPages.TMSLogger" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages.TMSLogger \- This class runs the logging functionality for all files in this solution\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLogIt\fP (string newLogString)"
.br
.RI "This is a list of logs stored locally\&. "
.ti -1c
.RI "static void \fBNewLog\fP (string newLogString)"
.br
.RI "This creates a new log object\&. "
.ti -1c
.RI "static bool \fBReadExistingLogFile\fP ()"
.br
.RI "Reads logs in from a file\&. "
.ti -1c
.RI "static bool \fBAppendLogFile\fP (\fBTMSLog\fP newLog)"
.br
.ti -1c
.RI "static void \fBLogIt\fP (string newLogString)"
.br
.ti -1c
.RI "static void \fBNewLog\fP (string newLogString)"
.br
.ti -1c
.RI "static bool \fBReadExistingLogFile\fP ()"
.br
.ti -1c
.RI "static bool \fBAppendLogFile\fP (\fBTMSLog\fP newLog)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBTMSLog\fP > \fBlogs\fP = new List<\fBTMSLog\fP>()"
.br
.RI "Stores location of the log file\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBLoggerPath\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBChangeLogLocation\fP ()"
.br
.RI "This function will change where the log file is stored\&. "
.ti -1c
.RI "static void \fBChangeLogLocation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class runs the logging functionality for all files in this solution\&. 

This is a static class containing a list of logs and the methods to create new logs\&. The main function of this class is to call the \fBTMSLog\fP class\&.
.PP
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "static bool TMSwPages\&.TMSLogger\&.AppendLogFile (\fBTMSLog\fP newLog)\fC [static]\fP"
Open the filestream to append to the file\&.
.PP
Add each log entry from the working list to the file as a BSV
.PP
Close the file
.PP
If an exception is thrown here, catch it
.PP
This could become problematic as it calls itself
.SS "static bool TMSwPages\&.TMSLogger\&.AppendLogFile (\fBTMSLog\fP newLog)\fC [static]\fP"
Open the filestream to append to the file\&.
.PP
Add each log entry from the working list to the file as a BSV
.PP
Close the file
.PP
If an exception is thrown here, catch it
.PP
This could become problematic as it calls itself
.SS "void TMSwPages\&.TMSLogger\&.ChangeLogLocation ()\fC [static]\fP, \fC [private]\fP"

.PP
This function will change where the log file is stored\&. This function allows the user to select a new location for the log file storage\&. Then the program copies the current file to the new location\&. If the copy is successful, the old file is deleted\&. Otherwise the old file is kept\&. 
.PP
\fBExceptions\fP
.RS 4
\fIFrom\fP FileStream and StreamReader / StreamWriter 
.RE
.PP
\fBSee also\fP
.RS 4

.br
 
.RE
.PP
\fBReturns\fP
.RS 4
Void
.RE
.PP
.PP
 
.SS "static void TMSwPages\&.TMSLogger\&.ChangeLogLocation ()\fC [static]\fP, \fC [private]\fP"

.SS "static public void TMSwPages\&.TMSLogger\&.LogIt (string newLogString)\fC [static]\fP"

.PP
This is a list of logs stored locally\&. This creates a new log object
.PP
This creates a new log object, adds it to the local list, then appends it to the external file 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP newLogString This is the unparsed BSV string to create the file\&. 
.RE
.PP
\fBSee also\fP
.RS 4
TMSLog(), logs\&.Add(), \fBAppendLogFile()\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 Error writing to Log File: Try once again
.SS "static void TMSwPages\&.TMSLogger\&.LogIt (string newLogString)\fC [static]\fP"
Error writing to Log File: Try once again
.SS "static public void TMSwPages\&.TMSLogger\&.NewLog (string newLogString)\fC [static]\fP"

.PP
This creates a new log object\&. This creates a new log object, and adds it to the local list\&. This exists so that the function ReadExistingLogFile doesn't call recursively\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP newLogString This is the unparsed BSV string to create the file\&. 
.RE
.PP
\fBSee also\fP
.RS 4
TMSLog(), logs\&.Add() 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 
.SS "static void TMSwPages\&.TMSLogger\&.NewLog (string newLogString)\fC [static]\fP"

.SS "static public bool TMSwPages\&.TMSLogger\&.ReadExistingLogFile ()\fC [static]\fP"

.PP
Reads logs in from a file\&. This clears the local log list then reads logs into it from the file specified by the loggerPath variable\&. If there is an error, it throws an exception to a new log\&. 
.PP
\fBExceptions\fP
.RS 4
\fIFrom\fP FileStream and StreamReader 
.RE
.PP
\fBSee also\fP
.RS 4
logs\&.Clear(), \fBNewLog()\fP, \fBLogIt()\fP 
.RE
.PP
\fBReturns\fP
.RS 4
bool readSuccess A value indicating whether the file read threw an exception\&.
.RE
.PP
.PP
 Clear out the working list
.PP
Open the file stream to read from the file
.PP
Fill the working list with lines from the file
.PP
Close the file
.PP
If an exception is thrown here, create a log for it\&.
.SS "static bool TMSwPages\&.TMSLogger\&.ReadExistingLogFile ()\fC [static]\fP"
Clear out the working list
.PP
Open the file stream to read from the file
.PP
Fill the working list with lines from the file
.PP
Close the file
.PP
If an exception is thrown here, create a log for it\&.
.SH "Member Data Documentation"
.PP 
.SS "static List< \fBTMSLog\fP > TMSwPages\&.TMSLogger\&.logs = new List<\fBTMSLog\fP>()\fC [static]\fP"

.PP
Stores location of the log file\&. 
.SH "Property Documentation"
.PP 
.SS "static string TMSwPages\&.TMSLogger\&.LoggerPath\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
