.TH "TMSwPages::ViewLogDetails" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages::ViewLogDetails
.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public \fBViewLogDetails\fP ()"
.br
.RI "Constructor for the \fBViewLogDetails\fP page\&. "
.ti -1c
.RI "public \fBViewLogDetails\fP (object data)"
.br
.RI "Alternative constructor for the \fBViewLogDetails\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public TMSwPages::ViewLogDetails::ViewLogDetails ()\fC [private]\fP"

.PP
Constructor for the \fBViewLogDetails\fP page\&. Initializes the page\&. 
.PP
\fBSee also\fP
.RS 4
InitializeComponent() 
.RE
.PP
\fBReturns\fP
.RS 4
N/A
.RE
.PP
.PP
 
.SS "public TMSwPages::ViewLogDetails::ViewLogDetails (object data)\fC [private]\fP"

.PP
Alternative constructor for the \fBViewLogDetails\fP\&. This constructor allows population of the page using data selected in a previous page\&. 
.PP
\fBParameters\fP
.RS 4
\fIobject\fP data this() The value in the datagrid selected in the previous page\&. 
.RE
.PP
\fBReturns\fP
.RS 4
N/A
.RE
.PP
.PP
 Bind to incoming log data\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
