.TH "TMSwPages.AlterTables" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages.AlterTables \- This class executes functions related to Altering Tables\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class executes functions related to Altering Tables\&. 

This class should be able to access, view, and change data in the Carrier Data Table, Route Table, and Rate / Fee Table
.PP
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
