.TH "TMSwPages::ViewLogDetailsPage" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages::ViewLogDetailsPage \- \fBViewLogDetailsPage\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page, and IComponentConnector\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "internal System Windows Controls Grid \fBOuterGrid\fP"
.br
.ti -1c
.RI "internal System Windows Controls RowDefinition \fBTopMenu\fP"
.br
.ti -1c
.RI "internal System Windows Controls RowDefinition \fBMain\fP"
.br
.ti -1c
.RI "internal System Windows Controls RowDefinition \fBButtons\fP"
.br
.ti -1c
.RI "internal System Windows Controls RowDefinition \fBStatusBar\fP"
.br
.ti -1c
.RI "internal System Windows Controls Menu \fBmyMenu\fP"
.br
.ti -1c
.RI "internal System Windows Controls ListBox \fBLogDetails\fP"
.br
.ti -1c
.RI "internal System Windows Controls Primitives StatusBarItem \fBstatusItem\fP"
.br
.ti -1c
.RI "internal System Windows Controls TextBlock \fBstatus\fP"
.br
.ti -1c
.RI "private bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBViewLogDetailsPage\fP 


.SH "Member Function Documentation"
.PP 
.SS "void System Windows Markup IComponentConnector TMSwPages::ViewLogDetailsPage::Connect (int connectionId, object target)\fC [private]\fP"

.SS "public void TMSwPages::ViewLogDetailsPage::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SH "Member Data Documentation"
.PP 
.SS "private bool TMSwPages::ViewLogDetailsPage::_contentLoaded\fC [private]\fP"

.SS "internal System Windows Controls RowDefinition TMSwPages::ViewLogDetailsPage::Buttons\fC [private]\fP"

.SS "internal System Windows Controls ListBox TMSwPages::ViewLogDetailsPage::LogDetails\fC [private]\fP"

.SS "internal System Windows Controls RowDefinition TMSwPages::ViewLogDetailsPage::Main\fC [private]\fP"

.SS "internal System Windows Controls Menu TMSwPages::ViewLogDetailsPage::myMenu\fC [private]\fP"

.SS "internal System Windows Controls Grid TMSwPages::ViewLogDetailsPage::OuterGrid\fC [private]\fP"

.SS "internal System Windows Controls TextBlock TMSwPages::ViewLogDetailsPage::status\fC [private]\fP"

.SS "internal System Windows Controls RowDefinition TMSwPages::ViewLogDetailsPage::StatusBar\fC [private]\fP"

.SS "internal System Windows Controls Primitives StatusBarItem TMSwPages::ViewLogDetailsPage::statusItem\fC [private]\fP"

.SS "internal System Windows Controls RowDefinition TMSwPages::ViewLogDetailsPage::TopMenu\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
