.TH "TMSwPages::AdminPage" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages::AdminPage \- This class runs the \fBAdminPage\fP UI functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SH "Detailed Description"
.PP 
This class runs the \fBAdminPage\fP UI functionality\&. 

This currently allows searching and updating of a local log list which is displayed to the screen\&. 
.br
.PP
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
