.TH "Transport_Management_System_WPF.Trip_Ticket" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.Trip_Ticket
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTicketID\fP"
.br
.ti -1c
.RI "\fBTruck\fP \fBTruckID\fP"
.br
.RI "The ticket ID Number\&. "
.ti -1c
.RI "bool \fBFTL_or_LTL\fP"
.br
.RI "The \fBTruck\fP that the ticket will attached to\&. "
.ti -1c
.RI "bool \fBIs_Reefer\fP"
.br
.RI "If the ticket is FTL or LTL\&. "
.ti -1c
.RI "int \fBSize_In_Palette\fP"
.br
.RI "If the ticket is reefer\&. "
.ti -1c
.RI "bool \fBIs_Complete\fP"
.br
.RI "Size of the ticket\&. "
.ti -1c
.RI "int \fBDays_Passed\fP"
.br
.RI "If the ticket is marked as complete\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.Trip_Ticket\&.Days_Passed"

.PP
If the ticket is marked as complete\&. 
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.FTL_or_LTL"

.PP
The \fBTruck\fP that the ticket will attached to\&. 
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.Is_Complete"

.PP
Size of the ticket\&. 
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.Is_Reefer"

.PP
If the ticket is FTL or LTL\&. 
.SS "int Transport_Management_System_WPF\&.Trip_Ticket\&.Size_In_Palette"

.PP
If the ticket is reefer\&. 
.SS "int Transport_Management_System_WPF\&.Trip_Ticket\&.TicketID"

.SS "\fBTruck\fP Transport_Management_System_WPF\&.Trip_Ticket\&.TruckID"

.PP
The ticket ID Number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
