.TH "Transport_Management_System_WPF::MainWindow" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF::MainWindow \- \fBMainWindow\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window, IComponentConnector, Window, IComponentConnector, and Window\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public \fBMainWindow\fP ()"
.br
.ti -1c
.RI "public void \fBSetOutput\fP (string outputString)"
.br
.ti -1c
.RI "private void \fBRedMenuItem_Click\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_Click_1\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_AddContract\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< \fBContract\fP > \fBacceptedContracts\fP = new List<\fBContract\fP>()"
.br
.ti -1c
.RI "internal System Windows Controls TabItem \fBBuyer\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBRedMenuItem\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBBlueMenuItem\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBOrangeMenuItem\fP"
.br
.ti -1c
.RI "internal System Windows Controls DataGrid \fBDG1\fP"
.br
.ti -1c
.RI "internal System Windows Controls DataGrid \fBDG2\fP"
.br
.ti -1c
.RI "internal System Windows Controls TabItem \fBPlanner\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBRed\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBBlue\fP"
.br
.ti -1c
.RI "internal System Windows Controls MenuItem \fBOrange\fP"
.br
.ti -1c
.RI "internal System Windows Controls DataGrid \fBDG3\fP"
.br
.ti -1c
.RI "internal System Windows Controls DataGrid \fBDG4\fP"
.br
.ti -1c
.RI "internal System Windows Controls TextBlock \fBOutput\fP"
.br
.ti -1c
.RI "private bool \fB_contentLoaded\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static public \fBBuyerClass\fP \fBbuyer\fP = new \fBBuyerClass\fP()"
.br
.ti -1c
.RI "static public string \fBa\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMainWindow\fP 

Interaction logic for MainWindow\&.xaml\&.
.PP
\&.\&.\&. static class? 
.br
.PP
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public Transport_Management_System_WPF::MainWindow::MainWindow ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "private void Transport_Management_System_WPF::MainWindow::Button_AddContract (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "private void Transport_Management_System_WPF::MainWindow::Button_Click (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "private void Transport_Management_System_WPF::MainWindow::Button_Click_1 (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "void System Windows Markup IComponentConnector Transport_Management_System_WPF::MainWindow::Connect (int connectionId, object target)\fC [private]\fP"

.SS "void System Windows Markup IComponentConnector Transport_Management_System_WPF::MainWindow::Connect (int connectionId, object target)\fC [private]\fP"

.SS "public void Transport_Management_System_WPF::MainWindow::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SS "public void Transport_Management_System_WPF::MainWindow::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SS "private void Transport_Management_System_WPF::MainWindow::RedMenuItem_Click (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "public void Transport_Management_System_WPF::MainWindow::SetOutput (string outputString)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "private bool Transport_Management_System_WPF::MainWindow::_contentLoaded\fC [private]\fP"

.SS "public string Transport_Management_System_WPF::MainWindow::a = ''\fC [static]\fP, \fC [private]\fP"

.SS "List<\fBContract\fP> Transport_Management_System_WPF::MainWindow::acceptedContracts = new List<\fBContract\fP>()\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::Blue\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::BlueMenuItem\fC [private]\fP"

.SS "public \fBBuyerClass\fP Transport_Management_System_WPF::MainWindow::buyer = new \fBBuyerClass\fP()\fC [static]\fP, \fC [private]\fP"

.SS "internal System Windows Controls TabItem Transport_Management_System_WPF::MainWindow::Buyer\fC [private]\fP"

.SS "internal System Windows Controls DataGrid Transport_Management_System_WPF::MainWindow::DG1\fC [private]\fP"

.SS "internal System Windows Controls DataGrid Transport_Management_System_WPF::MainWindow::DG2\fC [private]\fP"

.SS "internal System Windows Controls DataGrid Transport_Management_System_WPF::MainWindow::DG3\fC [private]\fP"

.SS "internal System Windows Controls DataGrid Transport_Management_System_WPF::MainWindow::DG4\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::Orange\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::OrangeMenuItem\fC [private]\fP"

.SS "internal System Windows Controls TextBlock Transport_Management_System_WPF::MainWindow::Output\fC [private]\fP"

.SS "internal System Windows Controls TabItem Transport_Management_System_WPF::MainWindow::Planner\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::Red\fC [private]\fP"

.SS "internal System Windows Controls MenuItem Transport_Management_System_WPF::MainWindow::RedMenuItem\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
