.TH "Transport_Management_System_WPF.MockupCMP" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.MockupCMP
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string[] \fBMockEntries\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string [] Transport_Management_System_WPF\&.MockupCMP\&.MockEntries\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
= {"|Hardware Depot|0|0|Belleville|Windsor|0|",
                                  "Atlantis Railway|1|3|Hamilton|Oshawa|0|",
                                  "Big Oil|0|0|Windsor|Hamilton|1|",
                                  "Rockomax Engineering|1|10|Belleville|Toronto|1|",
                                  "Space J|0|0|Toronto|Belleville|1|",
                                  "Rockomax Engineering|0|0|Belleville|Ottawa|1|",
                                  "Tom Hortons|0|0|Ottawa|Toronto|0|",
                                  "Sushi Noodle|0|0|Toronto|Ottawa|0",
                                  "Atlantis|Railway|0|0|Kingston|Windsor|0|"
        }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
