.TH "Transport_Management_System_WPF.TimePass" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.TimePass \- This class will be used to simulate the passage of time\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBIncrementDay\fP ()"
.br
.RI "This method will be used to simulate the passage of time\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class will be used to simulate the passage of time\&. 

This class is public and will be used by the \fBPlannerClass\fP
.PP
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "static void Transport_Management_System_WPF\&.TimePass\&.IncrementDay ()\fC [static]\fP"

.PP
This method will be used to simulate the passage of time\&. The data from each of the current trip tickets and their Route Data will be read from the data base\&. The time that each ticket has been alive will be used to determin the current location of the truck\&. This data will be daved back into the database\&. 
.PP
\fBParameters\fP
.RS 4
\fInull\fP 
.br
\fInull\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fInull\fP 
.RE
.PP
\fBSee also\fP
.RS 4
na 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
