.TH "Transport_Management_System_WPF" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdminPage\fP"
.br
.RI "\fBAdminPage\fP "
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml "
.ti -1c
.RI "class \fBBuyerClass\fP"
.br
.RI "This class runs the Buyer functionality\&. "
.ti -1c
.RI "class \fBCarrier\fP"
.br
.ti -1c
.RI "class \fBCityNode\fP"
.br
.RI "This class runs the \fBCityNode\fP functionality\&. "
.ti -1c
.RI "class \fBContract\fP"
.br
.RI "This class holds the contracts\&. "
.ti -1c
.RI "struct \fBCustomer\fP"
.br
.ti -1c
.RI "struct \fBLocation\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fBMainWindow\fP "
.ti -1c
.RI "class \fBMappingClass\fP"
.br
.RI "This class will be used by the planner to calculate route information for trip tickets\&. "
.ti -1c
.RI "class \fBmysqlConnector\fP"
.br
.RI "This class runs the Admin UI functionality\&. "
.ti -1c
.RI "class \fBPage1\fP"
.br
.RI "\fBPage1\fP "
.ti -1c
.RI "class \fBPlannerClass\fP"
.br
.RI "This class runs the \fBPlanner\fP functionality\&. "
.ti -1c
.RI "struct \fBRouteData\fP"
.br
.ti -1c
.RI "struct \fBRouteSumData\fP"
.br
.ti -1c
.RI "class \fBSQL_Query\fP"
.br
.RI "This class does all of the querys dealing with the cmp db\&. "
.ti -1c
.RI "class \fBSQL_Query_TMS\fP"
.br
.ti -1c
.RI "class \fBTimePass\fP"
.br
.RI "This class will be used to simulate the passage of time\&. "
.ti -1c
.RI "struct \fBTrip_Ticket\fP"
.br
.ti -1c
.RI "struct \fBTrip_Ticket_Line\fP"
.br
.ti -1c
.RI "struct \fBTruck\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
