.TH "Transport_Management_System_WPF::App" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF::App \- Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application, Application, and Application\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static public void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.ti -1c
.RI "static public void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml 

\fBApp\fP
.SH "Member Function Documentation"
.PP 
.SS "public void Transport_Management_System_WPF::App::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SS "public void Transport_Management_System_WPF::App::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SS "static public void Transport_Management_System_WPF::App::Main ()\fC [static]\fP, \fC [private]\fP"

.PP
Application Entry Point\&. 
.SS "static public void Transport_Management_System_WPF::App::Main ()\fC [static]\fP, \fC [private]\fP"

.PP
Application Entry Point\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
