.TH "Transport_Management_System_WPF.RouteSumData" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.RouteSumData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtotalDriveTime\fP"
.br
.ti -1c
.RI "double \fBtotalTripTime\fP"
.br
.ti -1c
.RI "int \fBtotalKM\fP"
.br
.ti -1c
.RI "int \fBOriginCity\fP"
.br
.ti -1c
.RI "int \fBDestinationCity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file MappingClass\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.RouteSumData\&.DestinationCity"

.PP
Definition at line 45 of file MappingClass\&.cs\&.
.SS "int Transport_Management_System_WPF\&.RouteSumData\&.OriginCity"

.PP
Definition at line 44 of file MappingClass\&.cs\&.
.SS "double Transport_Management_System_WPF\&.RouteSumData\&.totalDriveTime"

.PP
Definition at line 41 of file MappingClass\&.cs\&.
.SS "int Transport_Management_System_WPF\&.RouteSumData\&.totalKM"

.PP
Definition at line 43 of file MappingClass\&.cs\&.
.SS "double Transport_Management_System_WPF\&.RouteSumData\&.totalTripTime"

.PP
Definition at line 42 of file MappingClass\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
