.TH "Transport_Management_System_WPF.SQL_FAKEIT" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.SQL_FAKEIT
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< string >[] \fBSelect_Carriers\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SQL_FAKEIT\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<string> [] Transport_Management_System_WPF\&.SQL_FAKEIT\&.Select_Carriers ()"

.PP
Definition at line 30 of file SQL_FAKEIT\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
