.TH "Transport_Management_System_WPF::MainWindow" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public \fBMainWindow\fP ()"
.br
.ti -1c
.RI "public void \fBSetOutput\fP (string outputString)"
.br
.ti -1c
.RI "private void \fBRedMenuItem_Click\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_Click\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_Click_1\fP (object sender, RoutedEventArgs e)"
.br
.ti -1c
.RI "private void \fBButton_AddContract\fP (object sender, RoutedEventArgs e)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< \fBContract\fP > \fBacceptedContracts\fP = new List<\fBContract\fP>()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static public \fBBuyerClass\fP \fBbuyer\fP = new \fBBuyerClass\fP()"
.br
.ti -1c
.RI "static public string \fBa\fP = ''"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public Transport_Management_System_WPF::MainWindow::MainWindow ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "private void Transport_Management_System_WPF::MainWindow::Button_AddContract (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "private void Transport_Management_System_WPF::MainWindow::Button_Click (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "private void Transport_Management_System_WPF::MainWindow::Button_Click_1 (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "private void Transport_Management_System_WPF::MainWindow::RedMenuItem_Click (object sender, RoutedEventArgs e)\fC [private]\fP"

.SS "public void Transport_Management_System_WPF::MainWindow::SetOutput (string outputString)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "public string Transport_Management_System_WPF::MainWindow::a = ''\fC [static]\fP, \fC [private]\fP"

.SS "List<\fBContract\fP> Transport_Management_System_WPF::MainWindow::acceptedContracts = new List<\fBContract\fP>()\fC [private]\fP"

.SS "public \fBBuyerClass\fP Transport_Management_System_WPF::MainWindow::buyer = new \fBBuyerClass\fP()\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
