.TH "Transport_Management_System_WPF.Truck" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.Truck
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTruckID\fP"
.br
.ti -1c
.RI "int \fBCurrentCityID\fP"
.br
.ti -1c
.RI "bool \fBIs_Reefer\fP"
.br
.ti -1c
.RI "int \fBFree_Space\fP"
.br
.ti -1c
.RI "bool \fBWaiting_or_Transit\fP"
.br
.ti -1c
.RI "bool \fBFTL_or_LTL\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.Truck\&.CurrentCityID"

.SS "int Transport_Management_System_WPF\&.Truck\&.Free_Space"

.SS "bool Transport_Management_System_WPF\&.Truck\&.FTL_or_LTL"

.SS "bool Transport_Management_System_WPF\&.Truck\&.Is_Reefer"

.SS "int Transport_Management_System_WPF\&.Truck\&.TruckID"

.SS "bool Transport_Management_System_WPF\&.Truck\&.Waiting_or_Transit"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
