.TH "Transport_Management_System_WPF.Carrier" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.Carrier
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCarrier_Name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDepot_City\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBFTL_Rate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBLTL_Rate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBReefer_Charge\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file Carrier\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Transport_Management_System_WPF\&.Carrier\&.Carrier_Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 33 of file Carrier\&.cs\&.
.SS "string Transport_Management_System_WPF\&.Carrier\&.Depot_City\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file Carrier\&.cs\&.
.SS "float Transport_Management_System_WPF\&.Carrier\&.FTL_Rate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file Carrier\&.cs\&.
.SS "float Transport_Management_System_WPF\&.Carrier\&.LTL_Rate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 36 of file Carrier\&.cs\&.
.SS "float Transport_Management_System_WPF\&.Carrier\&.Reefer_Charge\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file Carrier\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
