.TH "Transport_Management_System_WPF.BuyerClass" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.BuyerClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBParseContracts\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file BuyerClass\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Transport_Management_System_WPF\&.BuyerClass\&.ParseContracts ()"

.PP
Definition at line 56 of file BuyerClass\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
