.TH "Transport_Management_System_WPF.RouteData" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.RouteData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBKM\fP"
.br
.ti -1c
.RI "double \fBPickupTime\fP"
.br
.ti -1c
.RI "double \fBDriveTime\fP"
.br
.ti -1c
.RI "double \fBLtlTime\fP"
.br
.ti -1c
.RI "double \fBDropoffTime\fP"
.br
.ti -1c
.RI "int \fBCityA\fP"
.br
.ti -1c
.RI "int \fBCityB\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.RouteData\&.CityA"

.SS "int Transport_Management_System_WPF\&.RouteData\&.CityB"

.SS "double Transport_Management_System_WPF\&.RouteData\&.DriveTime"

.SS "double Transport_Management_System_WPF\&.RouteData\&.DropoffTime"

.SS "int Transport_Management_System_WPF\&.RouteData\&.KM"

.SS "double Transport_Management_System_WPF\&.RouteData\&.LtlTime"

.SS "double Transport_Management_System_WPF\&.RouteData\&.PickupTime"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
