.TH "Transport_Management_System_WPF.PlannerClass" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.PlannerClass \- This class runs the \fBPlanner\fP functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlanner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class runs the \fBPlanner\fP functionality\&. 

This class will interface with the XAML main window to preform the \fBPlanner\fP tasks\&. This class will use many other classes to complete its task\&. At this point, much of the actual \fBPlannerClass\fP Functionality is obfuscated\&. Most of support classes have been complete\&.
.PP
\fBSee also\fP
.RS 4
\fBMappingClass\&.cs\fP \fBTimePass\&.cs\fP
.RE
.PP
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
