.TH "Transport_Management_System_WPF.SQL_Query" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.SQL_Query
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQL_Query\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "List< string >[] \fBSelect_Contracts\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file SQL_Query\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Transport_Management_System_WPF\&.SQL_Query\&.SQL_Query ()"

.PP
Definition at line 60 of file SQL_Query\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Transport_Management_System_WPF\&.SQL_Query\&.Initialize ()"

.PP
Definition at line 78 of file SQL_Query\&.cs\&.
.SS "List<string> [] Transport_Management_System_WPF\&.SQL_Query\&.Select_Contracts ()"

.PP
Definition at line 173 of file SQL_Query\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
