.TH "Transport_Management_System_WPF.Trip_Ticket" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.Trip_Ticket
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTicketID\fP"
.br
.ti -1c
.RI "\fBTruck\fP \fBTruckID\fP"
.br
.ti -1c
.RI "bool \fBFTL_or_LTL\fP"
.br
.ti -1c
.RI "bool \fBIs_Reefer\fP"
.br
.ti -1c
.RI "int \fBSize_In_Palette\fP"
.br
.ti -1c
.RI "bool \fBIs_Complete\fP"
.br
.ti -1c
.RI "double \fBDays_Passed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file PlannerClass\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "double Transport_Management_System_WPF\&.Trip_Ticket\&.Days_Passed"

.PP
Definition at line 54 of file PlannerClass\&.cs\&.
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.FTL_or_LTL"

.PP
Definition at line 50 of file PlannerClass\&.cs\&.
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.Is_Complete"

.PP
Definition at line 53 of file PlannerClass\&.cs\&.
.SS "bool Transport_Management_System_WPF\&.Trip_Ticket\&.Is_Reefer"

.PP
Definition at line 51 of file PlannerClass\&.cs\&.
.SS "int Transport_Management_System_WPF\&.Trip_Ticket\&.Size_In_Palette"

.PP
Definition at line 52 of file PlannerClass\&.cs\&.
.SS "int Transport_Management_System_WPF\&.Trip_Ticket\&.TicketID"

.PP
Definition at line 48 of file PlannerClass\&.cs\&.
.SS "\fBTruck\fP Transport_Management_System_WPF\&.Trip_Ticket\&.TruckID"

.PP
Definition at line 49 of file PlannerClass\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
