.TH "Transport_Management_System_WPF.Contract" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.Contract \- This class holds the contracts\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBToCityID\fP (string inputCity)"
.br
.RI "Converts a city name to the corresponding int\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< string > \fBnominatedCarriers\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclient_Name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBjob_Type\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBquantity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBorigin\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBdestination\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBvan_Type\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class holds the contracts\&. 

This class will mainly be used to pass contract data through out the application\&.
.PP
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.Contract\&.ToCityID (string inputCity)\fC [static]\fP"

.PP
Converts a city name to the corresponding int\&. This function converts a city to the corresponding int by comparing the input string to city names and outputs the proper value for the city\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP inputCity An incoming value meant to become the square's colour 
.br
\fInone\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBSee also\fP
.RS 4
none 
.RE
.PP
\fBReturns\fP
.RS 4
cityID in int format
.RE
.PP
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "List<string> Transport_Management_System_WPF\&.Contract\&.nominatedCarriers"

.SH "Property Documentation"
.PP 
.SS "string Transport_Management_System_WPF\&.Contract\&.client_Name\fC [get]\fP, \fC [set]\fP"

.SS "string Transport_Management_System_WPF\&.Contract\&.destination\fC [get]\fP, \fC [set]\fP"

.SS "bool Transport_Management_System_WPF\&.Contract\&.job_Type\fC [get]\fP, \fC [set]\fP"

.SS "string Transport_Management_System_WPF\&.Contract\&.origin\fC [get]\fP, \fC [set]\fP"

.SS "int Transport_Management_System_WPF\&.Contract\&.quantity\fC [get]\fP, \fC [set]\fP"

.SS "bool Transport_Management_System_WPF\&.Contract\&.van_Type\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
