.TH "Transport_Management_System_WPF.CityNode" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.CityNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCityNode\fP (string inName, int inCityId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCityID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCityName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCityNode\fP \fBEast\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBEastKM\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBEastHour\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCityNode\fP \fBWest\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBWestKM\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBWestHour\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Transport_Management_System_WPF\&.CityNode\&.CityNode (string inName, int inCityId)"

.SH "Property Documentation"
.PP 
.SS "int Transport_Management_System_WPF\&.CityNode\&.CityID\fC [get]\fP, \fC [set]\fP"

.SS "string Transport_Management_System_WPF\&.CityNode\&.CityName\fC [get]\fP, \fC [set]\fP"

.SS "\fBCityNode\fP Transport_Management_System_WPF\&.CityNode\&.East\fC [get]\fP, \fC [set]\fP"

.SS "double Transport_Management_System_WPF\&.CityNode\&.EastHour\fC [get]\fP, \fC [set]\fP"

.SS "int Transport_Management_System_WPF\&.CityNode\&.EastKM\fC [get]\fP, \fC [set]\fP"

.SS "\fBCityNode\fP Transport_Management_System_WPF\&.CityNode\&.West\fC [get]\fP, \fC [set]\fP"

.SS "double Transport_Management_System_WPF\&.CityNode\&.WestHour\fC [get]\fP, \fC [set]\fP"

.SS "int Transport_Management_System_WPF\&.CityNode\&.WestKM\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
