.TH "Transport_Management_System_WPF::AdminPage" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF::AdminPage \- \fBAdminPage\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page, and IComponentConnector\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent "
.ti -1c
.RI "void System Windows Markup IComponentConnector \fBConnect\fP (int connectionId, object target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "internal System Windows \fBControls\fP Grid \fBOuterGrid\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP RowDefinition \fBTopMenu\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP RowDefinition \fBTabs\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP RowDefinition \fBStatusBar\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP Menu \fBmyMenu\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TabItem \fBLogs\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP Grid \fBInnerGrid\fP"
.br
.ti -1c
.RI "internal System Windows Controls RowDefinition \fBControls\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP RowDefinition \fBMain\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP RowDefinition \fBButtons\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP ComboBox \fBTime_Period\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP DataGrid \fBLogsList\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TabItem \fBBackups\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TabItem \fBCarrier_Data\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TabItem \fBRoute_Table\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TabItem \fBRate_Fee_Tables\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP Primitives StatusBarItem \fBstatusItem\fP"
.br
.ti -1c
.RI "internal System Windows \fBControls\fP TextBlock \fBstatus\fP"
.br
.ti -1c
.RI "private bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAdminPage\fP 


.SH "Member Function Documentation"
.PP 
.SS "void System Windows Markup IComponentConnector Transport_Management_System_WPF::AdminPage::Connect (int connectionId, object target)\fC [private]\fP"

.SS "public void Transport_Management_System_WPF::AdminPage::InitializeComponent ()\fC [private]\fP"

.PP
InitializeComponent 
.SH "Member Data Documentation"
.PP 
.SS "private bool Transport_Management_System_WPF::AdminPage::_contentLoaded\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TabItem Transport_Management_System_WPF::AdminPage::Backups\fC [private]\fP"

.SS "internal System Windows \fBControls\fP RowDefinition Transport_Management_System_WPF::AdminPage::Buttons\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TabItem Transport_Management_System_WPF::AdminPage::Carrier_Data\fC [private]\fP"

.SS "internal System Windows Controls RowDefinition Transport_Management_System_WPF::AdminPage::Controls\fC [private]\fP"

.SS "internal System Windows \fBControls\fP Grid Transport_Management_System_WPF::AdminPage::InnerGrid\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TabItem Transport_Management_System_WPF::AdminPage::Logs\fC [private]\fP"

.SS "internal System Windows \fBControls\fP DataGrid Transport_Management_System_WPF::AdminPage::LogsList\fC [private]\fP"

.SS "internal System Windows \fBControls\fP RowDefinition Transport_Management_System_WPF::AdminPage::Main\fC [private]\fP"

.SS "internal System Windows \fBControls\fP Menu Transport_Management_System_WPF::AdminPage::myMenu\fC [private]\fP"

.SS "internal System Windows \fBControls\fP Grid Transport_Management_System_WPF::AdminPage::OuterGrid\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TabItem Transport_Management_System_WPF::AdminPage::Rate_Fee_Tables\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TabItem Transport_Management_System_WPF::AdminPage::Route_Table\fC [private]\fP"

.SS "internal System Windows \fBControls\fP TextBlock Transport_Management_System_WPF::AdminPage::status\fC [private]\fP"

.SS "internal System Windows \fBControls\fP RowDefinition Transport_Management_System_WPF::AdminPage::StatusBar\fC [private]\fP"

.SS "internal System Windows \fBControls\fP Primitives StatusBarItem Transport_Management_System_WPF::AdminPage::statusItem\fC [private]\fP"

.SS "internal System Windows \fBControls\fP RowDefinition Transport_Management_System_WPF::AdminPage::Tabs\fC [private]\fP"

.SS "internal System Windows \fBControls\fP ComboBox Transport_Management_System_WPF::AdminPage::Time_Period\fC [private]\fP"

.SS "internal System Windows \fBControls\fP RowDefinition Transport_Management_System_WPF::AdminPage::TopMenu\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
