.TH "Transport_Management_System_WPF.AlterTables" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Ciggies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.AlterTables
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 376 of file AdminClasses\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Ciggies from the source code\&.
