.TH "UnitTestTMS.PlannerClassTests.TestingContract" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestTMS.PlannerClassTests.TestingContract
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclient_Name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBjob_Type\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBquantity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBorigin\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBdestination\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBvan_Type\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.client_Name\fC [get]\fP, \fC [set]\fP"

.SS "int UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.destination\fC [get]\fP, \fC [set]\fP"

.SS "bool UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.job_Type\fC [get]\fP, \fC [set]\fP"

.SS "int UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.origin\fC [get]\fP, \fC [set]\fP"

.SS "string UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.quantity\fC [get]\fP, \fC [set]\fP"

.SS "string UnitTestTMS\&.PlannerClassTests\&.TestingContract\&.van_Type\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
