.TH "UnitTestTMS.UnitTest2" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTestTMS.UnitTest2 \- This class tests the Admin functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitTest2\fP ()"
.br
.ti -1c
.RI "void \fBTestAdminClasses1\fP ()"
.br
.RI "
.br
 "
.ti -1c
.RI "void \fBTestAdminClasses2\fP ()"
.br
.ti -1c
.RI "void \fBTestAdminClasses3\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TestContext \fBTestContext\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the test context which provides information about and functionality for the current test run\&. /summary> "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBTestContext\fP \fBtestContextInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class tests the Admin functionality\&. 

Currently tested files include: \fBAdminPage\&.xaml\&.cs\fP, \fBViewLogDetails\&.xaml\&.cs\fP, AdminClasses\&.cs
.PP
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnitTestTMS\&.UnitTest2\&.UnitTest2 ()"

.SH "Member Function Documentation"
.PP 
.SS "UnitTestTMS\&.UnitTest2\&.TestAdminClasses1 ()"

.PP

.br
 
.PP
\fBSee also\fP
.RS 4
AdminClasses\&.cs 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 Stores location of the log file
.PP
Test incorrect input string
.PP
Test correct input with 6 '|'
.PP
Test correct input with 7 '|'
.SS "void UnitTestTMS\&.UnitTest2\&.TestAdminClasses2 ()"
Stores location of the log file
.PP
Test incorrect input string
.PP
Test correct input with 6 '|'
.PP
Test correct input with 7 '|'
.PP
Add a new log with a blank string\&. This also appends to the log file\&.
.PP
Add a new log with a 5 piece input
.PP
Add a new log with a 6 piece input
.SS "void UnitTestTMS\&.UnitTest2\&.TestAdminClasses3 ()"
Stores location of the log file
.PP
Test incorrect input string
.PP
Test correct input with 6 '|'
.PP
Test correct input with 7 '|'
.PP
Add a new log with a blank string
.PP
Add a new log with a 5 piece input
.PP
Add a new log with a 6 piece input
.SH "Member Data Documentation"
.PP 
.SS "\fBTestContext\fP UnitTestTMS\&.UnitTest2\&.testContextInstance\fC [private]\fP"

.SH "Property Documentation"
.PP 
.SS "TestContext UnitTestTMS\&.UnitTest2\&.TestContext\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the test context which provides information about and functionality for the current test run\&. /summary> 

.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
