.TH "TMSwPages::AdminPage" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages::AdminPage \- This class runs the \fBAdminPage\fP UI functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "public \fBAdminPage\fP ()"
.br
.RI "This is a constructor for the \fBAdminPage\fP user interface\&. "
.ti -1c
.RI "private void \fBLoadClick\fP (object sender, RoutedEventArgs e)"
.br
.RI "This adds logs to the search results\&. "
.ti -1c
.RI "private void \fBViewMoreClick\fP (object sender, RoutedEventArgs e)"
.br
.RI "Sends the user to \fBViewLogDetails\fP page using selected \fBTMSLog\fP item's details\&. "
.ti -1c
.RI "private void \fBLogSettingsClick\fP (object sender, RoutedEventArgs e)"
.br
.RI "
.br
 "
.ti -1c
.RI "private void \fBTime_Period_SelectionChanged\fP (object sender, SelectionChangedEventArgs e)"
.br
.RI "METHOD HEADER COMMENT -------------------------------------------------------------------------------\&. "
.ti -1c
.RI "private void \fBDatePicker_SelectedDateChanged\fP (object sender, SelectionChangedEventArgs e)"
.br
.RI "
.br
 "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< \fBTMSLog\fP > \fBsearchResults\fP = new List<\fBTMSLog\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class runs the \fBAdminPage\fP UI functionality\&. 

This currently allows searching and updating of a local log list which is displayed to the screen\&. 
.br
.PP
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public TMSwPages::AdminPage::AdminPage ()\fC [private]\fP"

.PP
This is a constructor for the \fBAdminPage\fP user interface\&. This loads the searchResults TMSLogs into the LogsList data grid\&. 
.PP
\fBReturns\fP
.RS 4
Instantiates the \fBAdminPage\fP
.RE
.PP
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "private void TMSwPages::AdminPage::DatePicker_SelectedDateChanged (object sender, SelectionChangedEventArgs e)\fC [private]\fP"

.PP

.br
 
.br
 
.PP
\fBSee also\fP
.RS 4

.br
 
.RE
.PP
\fBReturns\fP
.RS 4

.br
.RE
.PP
.PP
 
.SS "private void TMSwPages::AdminPage::LoadClick (object sender, RoutedEventArgs e)\fC [private]\fP"

.PP
This adds logs to the search results\&. This adds logs to the search results which match search strings entered\&. This will first read from the Log file before it adds in any entries\&. This isn't done the most efficiently 
.PP
\fBExceptions\fP
.RS 4
\fIstring\&.Contains()\fP may throw an Argument Null exception 
.RE
.PP
\fBSee also\fP
.RS 4
\fBTMSLogger\&.LogIt()\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 This clears searchResults if the Log file is read in successfully
.PP
Compare search tags box to logs in the local list and add to searchResults list if matching
.PP
If there are no search strings, add indescriminately
.PP
Catch errors from Contains
.PP
Refresh the UI data grid
.SS "private void TMSwPages::AdminPage::LogSettingsClick (object sender, RoutedEventArgs e)\fC [private]\fP"

.PP

.br
 
.br
 
.PP
\fBSee also\fP
.RS 4

.br
 
.RE
.PP
\fBReturns\fP
.RS 4

.br
.RE
.PP
.PP
 
.SS "private void TMSwPages::AdminPage::Time_Period_SelectionChanged (object sender, SelectionChangedEventArgs e)\fC [private]\fP"

.PP
METHOD HEADER COMMENT -------------------------------------------------------------------------------\&. 
.br
.PP

.br
 
.PP
\fBSee also\fP
.RS 4

.br
 
.RE
.PP
\fBReturns\fP
.RS 4

.br
.RE
.PP
.PP
 
.SS "private void TMSwPages::AdminPage::ViewMoreClick (object sender, RoutedEventArgs e)\fC [private]\fP"

.PP
Sends the user to \fBViewLogDetails\fP page using selected \fBTMSLog\fP item's details\&. Does not activate if nothing is selected in the datagrid\&. 
.PP
\fBSee also\fP
.RS 4
NavigationService\&.Navigate() 
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "List<\fBTMSLog\fP> TMSwPages::AdminPage::searchResults = new List<\fBTMSLog\fP>()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
