.TH "TMSwPages" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSwPages
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdmin\fP"
.br
.RI "This class runs the \fBAdmin\fP UI functionality\&. "
.ti -1c
.RI "class \fBAdminPage\fP"
.br
.RI "This class runs the \fBAdminPage\fP UI functionality\&. "
.ti -1c
.RI "class \fBAlterTables\fP"
.br
.RI "This class executes functions related to Altering Tables\&. "
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml "
.ti -1c
.RI "class \fBBackupTMS\fP"
.br
.RI "This class executes the \fBAdmin\fP functions related to Backup\&. "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\\summary This is the Interaction Logic for the main nagivation window "
.ti -1c
.RI "class \fBTMSLog\fP"
.br
.RI "This class instantiates and stores a \fBTMSLog\fP object\&. "
.ti -1c
.RI "class \fBTMSLogger\fP"
.br
.RI "This class runs the logging functionality for all files in this solution\&. "
.ti -1c
.RI "class \fBViewLogDetails\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
