.TH "Transport_Management_System_WPF.SQL_Query" 3 "Fri Nov 22 2019" "Version 3.0" "TMS Project - 8000 Cigs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transport_Management_System_WPF.SQL_Query \- This class does all of the querys dealing with the cmp db\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQL_Query\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.RI "Sets all values for the sql connection\&. "
.ti -1c
.RI "List< string >[] \fBSelect_Contracts\fP ()"
.br
.RI "public function that pulls all contracts from database for the buyer\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBOpenConnection\fP ()"
.br
.RI "To create a new Square by validating or else defaulting new values\&. "
.ti -1c
.RI "bool \fBCloseConnection\fP ()"
.br
.RI "Closes the connection to the SQL database server\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "MySqlConnection \fBconnection\fP"
.br
.ti -1c
.RI "string \fBserver\fP"
.br
.ti -1c
.RI "string \fBdatabase\fP"
.br
.ti -1c
.RI "string \fBuid\fP"
.br
.ti -1c
.RI "string \fBpassword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class does all of the querys dealing with the cmp db\&. 

public class\&. 
.br
.PP
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "void Transport_Management_System_WPF\&.SQL_Query\&.SQL_Query ()"

.PP
Constructor\&. Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP 
.br
\fInone\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBSee also\fP
.RS 4
\fBInitialize()\fP 
.RE
.PP
\fBReturns\fP
.RS 4
None
.RE
.PP
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "bool Transport_Management_System_WPF\&.SQL_Query\&.CloseConnection ()\fC [private]\fP"

.PP
Closes the connection to the SQL database server\&. Closes the connection to the SQL database server and outputs an exeption to the log and to the screen if a exception is thrown\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP 
.br
\fInone\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIMySqlException\fP 
.RE
.PP
\fBSee also\fP
.RS 4
connection\&.Close() 
.RE
.PP
\fBReturns\fP
.RS 4
None
.RE
.PP
.PP
 
.SS "void Transport_Management_System_WPF\&.SQL_Query\&.Initialize ()"

.PP
Sets all values for the sql connection\&. Sets all values for the sql connection\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP 
.br
\fInone\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fInone\fP should be thrown 
.RE
.PP
\fBSee also\fP
.RS 4
none 
.RE
.PP
\fBReturns\fP
.RS 4
None
.RE
.PP
.PP
 
.SS "bool Transport_Management_System_WPF\&.SQL_Query\&.OpenConnection ()\fC [private]\fP"

.PP
To create a new Square by validating or else defaulting new values\&. THis is if you have more to say about what the function does and don't want to inline comment 
.PP
\fBParameters\fP
.RS 4
\fInone\fP 
.br
\fInone\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIMySqlException\fP ex, 0: Cannot connect to server\&. Contact administrator / 1: Invalid username/password, please try again 
.RE
.PP
\fBSee also\fP
.RS 4
CallsMade() 
.RE
.PP
\fBReturns\fP
.RS 4
None
.RE
.PP
.PP
 
.SS "Transport_Management_System_WPF\&.SQL_Query\&.Select_Contracts ()"

.PP
public function that pulls all contracts from database for the buyer\&. Pulls all contracts from database usinhg mysql querys and populates a list which and returns the list\&. 
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.br
\fIvoid\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIno\fP exceptions should be thrown\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBBuyerClass\fP Class 
.RE
.PP
\fBReturns\fP
.RS 4
List<string>[]
.RE
.PP
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "MySqlConnection Transport_Management_System_WPF\&.SQL_Query\&.connection\fC [private]\fP"

.SS "string Transport_Management_System_WPF\&.SQL_Query\&.database\fC [private]\fP"

.SS "string Transport_Management_System_WPF\&.SQL_Query\&.password\fC [private]\fP"

.SS "string Transport_Management_System_WPF\&.SQL_Query\&.server\fC [private]\fP"

.SS "string Transport_Management_System_WPF\&.SQL_Query\&.uid\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TMS Project - 8000 Cigs from the source code\&.
